### ISSUE TITLE
要是主题能发布npm包就更方便了

### ISSUE THREAD

**Issue by twitf** [17px/hexo-theme-cosy#1]

**Comment by 17px** [comment]
@twitf 真是好主意，今后迭代会实现这个

**Comment by twitf** [comment]
```bash
PS D:\wwwroot\mozzieBlog> hexo algolia
INFO  Validating config
INFO  Start processing
INFO  Files loaded in 187 ms
INFO  0 files generated in 152 ms
INFO  Clearing index on Algolia...
INFO  Index cleared.
INFO  Indexing posts on Algolia...
INFO  Error has occurred during indexing posts : [object Object]
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
```

这是我的配置 还有插件我i都装了
![Uploading Snipaste_2023-11-10_10-52-59.png…]()

**Comment by 17px** [comment]
图片似乎失效了，可以按照如下步骤检查一下

[1.2.7版本](https://github.com/17px/hexo-theme-cosy/releases/download/v1.2.7/hexo-theme-cosy.zip) 使用的是：`"hexo-algoliasearch-next": "1.0.2"`插件，来建立全部内容的索引，上报给algolia。

## 安装
`npm install hexo-algoliasearch-next --save`

## algolia配置
```yaml
algolia:
  # 替换
  appId: Application ID
  # 替换
  apiKey: Usage API Key
  # 请勿泄露，用于上报，替换
  adminApiKey: Admin API Key
  # 替换
  SearchOnlyAPIKey: Search-Only API Key
  chunkSize: 5000
  # 替换
  indexName: your-index-name
  fields:
    - content
    - excerpt:strip
    - categories
    - title
    - permalink
    - slug
    - tags
    - title
```

😁请试试按照上面的配置修改一下，看看是否可以解决问题

**Comment by twitf** [comment]
```
PS D:\wwwroot\mozzieBlog> hexo algolia
INFO  Validating config
INFO  Start processing
INFO  Files loaded in 186 ms
INFO  0 files generated in 154 ms
INFO  Clearing index on Algolia...
INFO  Index cleared.
INFO  Indexing posts on Algolia...
INFO  Error has occurred during indexing posts : [object Object]
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
```
还是这样,还有一个问题 这个语法高亮你是代码里固定使用`highlight`吗，我的配置如下：
```yml
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false

prismjs:
  enable: true
  preprocess: true
  line_number: true
  tab_replace: ''
```

然后渲染生成的高亮还是用的highlight，我确认这不是缓存，hexo clean && hexo g&& hexo s

```html
<figure class="highlight php"><table><tbody><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br></pre></td><td class="code"><pre><span class="line"><span class="title function_ invoke__">str_contains</span>(<span class="string">"abc"</span>, <span class="string">"a"</span>); <span class="comment">// true</span></span><br><span class="line"><span class="title function_ invoke__">str_contains</span>(<span class="string">"abc"</span>, <span class="string">"d"</span>); <span class="comment">// false</span></span><br><span class="line"> </span><br><span class="line"><span class="comment">// 空字符串是，都是返回true</span></span><br><span class="line"><span class="title function_ invoke__">str_contains</span>(<span class="string">"abc"</span>, <span class="string">""</span>);  <span class="comment">// true</span></span><br><span class="line"><span class="title function_ invoke__">str_contains</span>(<span class="string">""</span>, <span class="string">""</span>);     <span class="comment">// true</span></span><br></pre></td></tr></tbody></table></figure>
```

这个主题很漂亮 我很想使用它，但是这些问题导致我无法体验到他的完美

**Comment by 17px** [comment]
> ```
> PS D:\wwwroot\mozzieBlog> hexo algolia
> INFO  Validating config
> INFO  Start processing
> INFO  Files loaded in 186 ms
> INFO  0 files generated in 154 ms
> INFO  Clearing index on Algolia...
> INFO  Index cleared.
> INFO  Indexing posts on Algolia...
> INFO  Error has occurred during indexing posts : [object Object]
> FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
> ```
> 
> 还是这样,还有一个问题 这个语法高亮你是代码里固定使用`highlight`吗，我的配置如下：
> 
> ```yaml
> highlight:
>   enable: false
>   line_number: true
>   auto_detect: false
>   tab_replace: ''
>   wrap: true
>   hljs: false
> 
> prismjs:
>   enable: true
>   preprocess: true
>   line_number: true
>   tab_replace: ''
> ```
> 
> 然后渲染生成的高亮还是用的highlight，我确认这不是缓存，hexo clean && hexo g&& hexo s
> 
> ```
> <figure class="highlight php"><table><tbody><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br></pre></td><td class="code"><pre><span class="line"><span class="title function_ invoke__">str_contains</span>(<span class="string">"abc"</span>, <span class="string">"a"</span>); <span class="comment">// true</span></span><br><span class="line"><span class="title function_ invoke__">str_contains</span>(<span class="string">"abc"</span>, <span class="string">"d"</span>); <span class="comment">// false</span></span><br><span class="line"> </span><br><span class="line"><span class="comment">// 空字符串是，都是返回true</span></span><br><span class="line"><span class="title function_ invoke__">str_contains</span>(<span class="string">"abc"</span>, <span class="string">""</span>);  <span class="comment">// true</span></span><br><span class="line"><span class="title function_ invoke__">str_contains</span>(<span class="string">""</span>, <span class="string">""</span>);     <span class="comment">// true</span></span><br></pre></td></tr></tbody></table></figure>
> ```
> 
> 这个主题很漂亮 我很想使用它，但是这些问题导致我无法体验到他的完美

1. 我注意到了，你的使用 `hexo algolia` 命令的日志有一行，是：

`0 files generated in 154 ms`，这或许导致了索引建立失败，可以提供一下 `hexo 根目录` 的 `db.json` 内部文本吗？

2. 代码语法高亮如果不生效，请检查配置是否在 hexo 的`_config.yml`中，而不是主题文件夹的 `_config.yml` 中，或者是否有什么别的插件冲突

```yaml
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false

prismjs:
  enable: true
  preprocess: true
  line_number: true
  tab_replace: ''
```

**Comment by twitf** [comment]
1：[db.json](https://github.com/17px/hexo-theme-cosy/files/13316016/db.json)
这是我的db.json.麻烦帮忙看看是什么原因

2。还有代码语法高亮配置我实在hexo根目录下的配置文件加的，不是theme下的配置文件

**Comment by 17px** [comment]
> 1：[db.json](https://github.com/17px/hexo-theme-cosy/files/13316016/db.json) 这是我的db.json.麻烦帮忙看看是什么原因
> 
> 2。还有代码语法高亮配置我实在hexo根目录下的配置文件加的，不是theme下的配置文件

1. db.json看起来没有什么问题，也许你可以试试查看 [hexo-algoliasearch-next](https://www.npmjs.com/package/hexo-algoliasearch-next)，试试修改`fields` 配置，例如： `content` 修改为 `content:strip:truncate,0,500`，或者删除、调整其他的配置项，再试一试

```yaml
algolia:
  fields:
    - content:strip:truncate,0,500
    - excerpt:strip
    - categories
    - title
    - permalink
    - slug
    - tags
    - title
```

2. 抱歉，经过测试，似乎在 hexo 版本为 `7.0.0`的情况下，prism语法高亮配置会失效，在`6.3.0` 是可以的，因此，可以修改`package.json`中的 `hexo` 版本为 `6.3.0`，然后执行 `hexo cl & hexo g`，试一下😁
